Pickup.com/Controllers/BuyerController.cs
using DataAccess;
using DataAccess.Repository;
using Pickup.com.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pickup.com.Controllers
{
    public class BuyerController : Controller
    {
        // GET: Buyer
        BuyerRepository buyerRepo = new BuyerRepository();
        AreaRepository areaRepo = new AreaRepository();
        CityRepository cityRepo = new CityRepository();
        BuyerAddressRepository addressRepo = new BuyerAddressRepository();
        BuyerApprovalRepository approvalRepo = new BuyerApprovalRepository();
        ProductCartRepository cartRepo = new ProductCartRepository();
        ProductRepository productRepo = new ProductRepository();

        public ActionResult Index(int id)
        {
            Buyer buyer = buyerRepo.GetByLogin(id);
            BuyerApproval approval = approvalRepo.Get(buyer.ApprovalId);

            if (approval.Status)
            {
                Session["BID"] = buyer.BuyerId;

                if (InitCart()==1)
                {
                    return RedirectToAction("Index", "Home");
                }
                
                else return View("Error");
            }

            else return View("Error");
        }

        public ActionResult ViewProfile(int id)
        {
            Buyer buyer = buyerRepo.Get(id);
           
            return View(buyer);
        }

        [HttpGet]
        public ActionResult Create()
        {
            List<SelectListItem> areaList = new List<SelectListItem>();
            List<SelectListItem> cityList = new List<SelectListItem>();

            foreach (Area area in areaRepo.GetAll())
            {
                SelectListItem option = new SelectListItem();
                option.Text = area.Name;
                option.Value = area.Id.ToString();

                areaList.Add(option);
            }

            foreach (City city in cityRepo.GetAll())
            {
                SelectListItem option = new SelectListItem();
                option.Text = city.Name;
                option.Value = city.Id.ToString();

                cityList.Add(option);
            }

            ViewBag.Area = areaList;
            ViewBag.City = cityList;

            return View();
        }

        [HttpPost]
        public ActionResult Create(ViewBuyer vbuyer)
        {
            if (ModelState.IsValid)
            {
                BuyerAddress address = new BuyerAddress();
                address.Area = areaRepo.Get(vbuyer.Area);
                address.City = cityRepo.Get(vbuyer.City);
                address.Block = vbuyer.Block;
                address.House = vbuyer.House;
                address.Road = vbuyer.House;

                BuyerLogin login = new BuyerLogin();
                login.Username = vbuyer.Username;
                login.Password = vbuyer.Password;

                BuyerApproval approval = new BuyerApproval();
                approval.Status = false;

                Buyer buyer = new Buyer();
                buyer.FirstName = vbuyer.FirstName;
                buyer.LastName = vbuyer.LastName;
                buyer.Email = vbuyer.Email;
                buyer.Phone = vbuyer.Phone;
                buyer.Gender = vbuyer.Gender;
                buyer.Address = address;
                buyer.LoginData = login;
                buyer.Approval = approval;

                buyerRepo.Insert(buyer);

                return RedirectToAction("Index","Home");
            }
           
            return View(vbuyer);
        }

        public ActionResult Logout()
        {
            Session["BID"] = null;
            return RedirectToAction("Index", "Home");
        }

        [NonAction]
        private int InitCart()
        {
            if (Session["BID"] != null)
            {
                ProductCart cart =  new ProductCart();
                cart.BuyerId = (int)Session["BID"];
                Session["CART"] = cart;

                return 1;
            }

            else return 0;
        }
    }
}

Pickup.com/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title></title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="style.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>
    <!-- NavBar -->
    <nav class="navbar navbar-inverse container-fluid">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Home/Index">Pickup.com</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="#">Contact Admin</a></li>
                    <li><a href="#">About</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <!-- Body start -->
    <div class="container-fluid">
        <div class="row">

            <div class="col-xs-9">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="container-fluid text-center bg-lightgray">

        <div class="copyrights" style="margin-top:25px;">
            <p>
                Md. Hasan Uzzaman © 2017, All Rights Reserved
                <br>
                <span>Design By: Md. Hasan Uzzaman Noyon</span>
            </p>
            <p>
        </div>
    </footer>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

Pickup.com/Views/Shared/_LayoutBuyer.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title></title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="style.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- NavBar -->
    <nav class="navbar navbar-inverse container-fluid">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/Home/Index">Home <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Link-1</a></li>
            <li><a href="#">Link-2</a></li>
            <li><a href="#">Link-3</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li>@Html.ActionLink("Logout","Logout","Buyer")</li>
                      <li role="separator" class="divider"></li>
                  </ul>
              </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- Body start -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-3 sidebar">
          <h3>Sidebar</h3>
            <ul class="nav nav-tabs nav-stacked">
              <li><a href='#'>Another Link 1</a></li>
              <li><a href='#'>Another Link 2</a></li>
              <li><a href='#'>Another Link 3</a></li>
            </ul>
        </div>
        <div class="col-xs-9">
            @RenderBody()
        </div>
      </div>
    </div>

    <footer class="container-fluid text-center bg-lightgray">

            <div class="copyrights" style="margin-top:25px;">
                <p>Md. Hasan Uzzaman © 2017, All Rights Reserved
                    <br>
                    <span>Design By: Md. Hasan Uzzaman Noyon</span></p>
                <p>
            </div>
    </footer>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

Pickup.com/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title></title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->

      <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

      <link href="~/Content/style.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- NavBar -->
    <nav class="navbar navbar-inverse container-fluid">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/Home/Index">Pickup.com</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control dhon" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>
          <ul class="nav navbar-nav">
            <li><a href="#">Contact Admin</a></li>
            <li><a href="#">About</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login / Register <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li>@Html.ActionLink("Login","Login")</li>
                      <li role="separator" class="divider"></li>
                      <li>@Html.ActionLink("Register As Buyer","CreateBuyer")</li>
                      <li>@Html.ActionLink("Register As Seller","CreateSeller")</li>
                  </ul>
              </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- Body start -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-3 sidebar">
          <h3>Sidebar</h3>
            <ul class="nav nav-tabs nav-stacked">
                <ul class="nav nav-tabs nav-stacked">
                    <li>@Html.ActionLink("Men Cloths", "ViewCatagory", new { id = 1 }, new { @class = "btn btn-primary btn-large" })</li>
                    <li>@Html.ActionLink("Women Cloths", "ViewCatagory", new { id = 2 }, new { @class = "btn btn-primary btn-large" })</li>
                    <li>@Html.ActionLink("Electronics", "ViewCatagory", new { id = 3 }, new { @class = "btn btn-primary btn-large" })</li>
                    <li>@Html.ActionLink("Home Appliences", "ViewCatagory", new { id = 4 }, new { @class = "btn btn-primary btn-large" })</li>
                    <li>@Html.ActionLink("Others", "ViewCatagory", new { id = 5 }, new { @class = "btn btn-primary btn-large" })</li>
                </ul>
            </ul>
        </div>
        <div class="col-xs-9">
            @RenderBody()
        </div>
      </div>
    </div>

    <footer class="container-fluid text-center bg-lightgray">

            <div class="copyrights" style="margin-top:25px;">
                <p>Md. Hasan Uzzaman © 2017, All Rights Reserved
                    <br>
                    <span>Design By: Md. Hasan Uzzaman Noyon</span></p>
                <p>
            </div>
    </footer>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>