Pickup.com/Controllers/MamaController.cs
using DataAccess;
using DataAccess.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pickup.com.Controllers
{
    public class MamaController : Controller
    {
        MamaRepository mamaRepo = new MamaRepository();
        EmployeeApprovalRepository approvalRepo = new EmployeeApprovalRepository();
        
        // GET: Mama
        public ActionResult Index(int id)
        {
            Mama mama = mamaRepo.GetByLogin(id);
            EmployeeApproval approval = approvalRepo.Get(mama.ApprovalId);

            if (approval.Status)
            {
                Session["MID"] = mama.Id;
                return View(mama);
            }

            else return View("Error");    
        }

        public ActionResult ViewOrders()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session["MID"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

Pickup.com/Views/Shared/Mama/_LayoutMama.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title></title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="style.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- NavBar -->
    <nav class="navbar navbar-inverse container-fluid">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/Employee/Index">Pickup.com</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li>@Html.ActionLink("Profile","ViewProfile")</li>
                      <li role="separator" class="divider"></li>
                      <li>@Html.ActionLink("Log Out", "Logout")</li>
                  </ul>
              </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- Body start -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-3 sidebar">
          <h3>Sidebar</h3>
            <ul class="nav nav-tabs nav-stacked">
                <li>@Html.ActionLink("View Orders", "ViewOrders", "Mama", null, new { @class = "btn btn-primary btn-large" })</li>
            </ul>
        </div>
        <div class="col-xs-9">
            @RenderBody()
        </div>
      </div>
    </div>

    <footer class="container-fluid text-center bg-lightgray">

            <div class="copyrights" style="margin-top:25px;">
                <p>Md. Hasan Uzzaman © 2017, All Rights Reserved
                    <br>
                    <span>Design By: Md. Hasan Uzzaman Noyon</span></p>
                <p>
            </div>
    </footer>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>